baseURL = "/"
languageCode = "en-us"
title = "Kyle Kochanek"

# Directory paths
contentDir = "src/content"
layoutDir = "src/layouts"
assetDir = "src/assets"
staticDir = "src/static"
dataDir = "src/data"
archetypeDir = ".hugorc/archetypes"

[params]
  description = "Kyle's online space for his portfolio and different musing on design and craft."
  author = "Kyle Kochanek"

[menu]
  [[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 1
  [[menu.main]]
    name = "Now"
    url = "/now/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[build]
  writeStats = true
  [build.processing]
    skip_processing = false
    [build.processing.css]
      method = "sass"
      options = "expanded"
      includePaths = ["src/assets/scss"]

[module]
  [[module.mounts]]
    source = "src/assets"
    target = "assets"

[build.buildStats]
  enable = true

[markup.goldmark.renderer]
  unsafe = true

[imaging]
  quality = 64
  resampleFilter = "Lanczos"
  anchor = "Smart"
  format = "webp"  # Default format for image processing

[imaging.exif]
  includeFields = ""

[caches]
  [caches.images]
    dir = ":resourceDir/_gen"
    maxAge = "720h"

[server]
  [[server.headers]]
    for = "/*.webp"
    [server.headers.values]
      Cache-Control = "public, max-age=31536000"

[imaging.webp]
quality = 80