baseURL = "/"
languageCode = "en-us"
title = "Kyle Kochanek"

[params]
  description = "Kyle's online space for his portfolio and different musing on design and craft."
  author = "Kyle Kochanek"

[menu]
  [[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Resume ↓"
    url = "/assets/files/Kyle_Kochanek_Resume.pdf"
    weight = 3

[build]
  writeStats = true
  [build.processing]
    skip_processing = false
    [build.processing.css]
      method = "sass"
      options = "expanded"
      includePaths = ["assets/scss"]

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"

[build.buildStats]
  enable = true

[markup.goldmark.renderer]
  unsafe = true

[imaging]
  quality = 90
  resampleFilter = "lanczos"
  anchor = "smart"
  format = "webp"  # Default format for image processing

[imaging.exif]
  disableDate = true
  disableLatLong = true

[caches]
  [caches.images]
    dir = ":resourceDir/_gen"
    maxAge = "720h"

[server]
  [[server.headers]]
    for = "/*.webp"
    [server.headers.values]
      Cache-Control = "public, max-age=31536000"