[build]
  publish = "public"
  command = """
    npm ci && \
    hugo --gc --minify && \
    chmod +x validate-deployment.sh && \
    hugo server --port 8080 --bind 0.0.0.0 --disableFastRender & \
    HUGO_PID=$! && \
    sleep 10 && \
    HUGO_TEST_PORT=8080 timeout 30s ./validate-deployment.sh && \
    kill $HUGO_PID || true
  """

[build.environment]
  HUGO_VERSION = "0.148.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  HUGO_EXTENDED = "true"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self'; \
      style-src 'self' 'unsafe-inline' fonts.googleapis.com; \
      script-src 'self' 'unsafe-inline' cdn.jsdelivr.net *.services-prod.nsvcs.net; \
      font-src 'self' fonts.gstatic.com; \
      connect-src 'self' *.services-prod.nsvcs.net; \
      img-src 'self' data: *.services-prod.nsvcs.net\
    """

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"