[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.138.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  HUGO_EXTENDED = "true"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self'; \
      style-src 'self' 'unsafe-inline' fonts.googleapis.com; \
      script-src 'self' 'unsafe-inline' cdn.jsdelivr.net *.services-prod.nsvcs.net; \
      font-src 'self' fonts.gstatic.com; \
      connect-src 'self' *.services-prod.nsvcs.net; \
      img-src 'self' data: *.services-prod.nsvcs.net\
    """
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"