name: Accessibility Check

on:
  pull_request:
    branches:
      - main

jobs:
  pa11y:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.138.0'
        extended: true

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ make

    - name: Build the site
      run: hugo --verbose

    - name: Serve the site
      run: hugo server --port 3000 &

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Pa11y
      run: npm install -g pa11y

    - name: Run Pa11y
      run: pa11y http://localhost:3000 --reporter html > pa11y-report.html
