name: Accessibility Check

on:
  pull_request:
    branches:
      - main

jobs:
  pa11y:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.138.0'
        extended: true

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc g++ make chromium-browser

    - name: Build the site
      run: hugo --verbose

    - name: Serve the site
      run: hugo server --port 3000 --bind 0.0.0.0 &

    - name: Wait for Hugo server
      run: |
        echo "Waiting for Hugo server to be ready..."
        timeout 30 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:3000)" != "200" ]]; do sleep 2; done' || false

    - name: Install Pa11y
      run: |
        npm install -g pa11y puppeteer

    - name: Run Pa11y
      env:
        PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
      run: |
        pa11y http://localhost:3000 \
          --reporter html \
          --wait 1000 \
          --timeout 60000 \
          > pa11y-report.html

    - name: Upload Pa11y report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: pa11y-report
        path: pa11y-report.html
