name: Accessibility Check

on:
  pull_request:
    branches:
      - main

jobs:
  pa11y:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build the site
      run: hugo

    - name: Serve the site
      run: hugo server --port 3000 &

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Pa11y
      run: npm install -g pa11y

    - name: Run Pa11y
      run: pa11y http://localhost:3000 --reporter html > pa11y-report.html
